version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatdb
    ports:
      - "5435:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: chat_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemple-chat.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"   # pgAdmin accessible sur http://localhost:8080
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

volumes:
  postgres_data:
